apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-with-pod-anti-affinity
  name: nginx-with-pod-anti-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-with-pod-anti-affinity
  template:
    metadata:
      labels:
        app: nginx-with-pod-anti-affinity
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:1.19.5
        name: nginx
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx-with-pod-anti-affinity
              topologyKey: kubernetes.io/hostname
